---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: add elastic key
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
  rpm_key: >
    key=https://packages.elastic.co/GPG-KEY-elasticsearch
    state=present

- name: add elastic key
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  apt_key: >
    url=https://packages.elastic.co/GPG-KEY-elasticsearch
    id=D88E42B4
    state=present

- name: setup pkg mgr
  become: yes
  become_user: root
  register: logstash_pkg_mgr_configured
  with_items: '{{logstash_templates}}'
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644

- name: update pkg mgr
  become: yes
  become_user: root
  when: ansible_os_family == 'Debian' and logstash_pkg_mgr_configured|changed
  apt: update_cache=yes

- name: install logstash
  become: yes
  become_user: root
  package: name=logstash state=present

- name: configure...
  become: yes
  become_user: root
  with_items: '{{config_files}}'
  template: >-
    src=etc/logstash/conf.d/{{item}}.j2
    dest=/etc/logstash/conf.d/{{item}}
    mode=0644

- name: boot logstash service
  become: yes
  become_user: root
  service: name=logstash enabled=yes state=started
