---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'
- name: check for logstash installation
  become: yes
  stat:
    path: '{{logstash_install_dir}}'
  changed_when: false
  register: logstash_binary_dir
- when: not logstash_binary_dir.stat.exists
  block:
    - name: download...
      become: yes
      become_user: root
      get_url:
        url: '{{logstash_tgz_url}}'
        dest: /tmp/{{logstash_tgz}}
        checksum: '{{logstash_checksum}}'
        mode: 0644
    - name: unarchive...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{logstash_tgz}}
        dest: '{{logstash_parent_install_dir}}'
        creates: '{{logstash_install_dir}}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{logstash_tgz}}
        state: absent

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{logstash_install_dir}}'
    dest: '{{logstash_link_dir}}'
    state: link

- name: add to default path...
  become: yes
  become_user: root
  with_items:
    - f: logstash.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'

