---
- name: EL...
  when: ansible_os_family == 'RedHat'
  include: EL.yml

- name: Debian...
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: configure...
  template: >-
    src=etc/logstash/conf.d/logstash.conf.j2
    dest=/etc/logstash/conf.d/logstash.conf
    owner=root
    group=root
    mode=0644

- name: boot logstash service
  service: name=logstash enabled=yes state=started
